# SITE SETUP
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Site Description
description: 'Code experiments and thoughts on Bitcoin, Cognitive Computing, and Virtual Production'

# Author
author:
  name: 'Daniel Leston'
  bio: 'Thinker, Builder, Holder - Exploring Bitcoin, Cognitive Computing & Virtual Production'
  avatar: '/content/authors/admin/avatar.png'

# Social Links
social:
  - name: 'Twitter/X'
    url: 'https://x.com/BuildLore'
  - name: 'GitHub'
    url: 'https://github.com/dfleston'
  twitter: 'df_leston'

# Site header
header:
  navbar:
    enable: true
    show_search: true
    show_theme_chooser: true

# Site footer
footer:
  copyright:
    notice: 'Â© {year} Me. This work is licensed under {license}'
    year: '2025'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

   
      

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/HugoBlox/hugo-blox-builder/'
    content_dir: templates/blog/content
    branch: main
